[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
smart_contracts = "CQcG2qZooAYoeE96ZYKJd3omq2DPWHozSceSnuCxRv8U"

[programs.devnet]
smart_contracts = "CQcG2qZooAYoeE96ZYKJd3omq2DPWHozSceSnuCxRv8U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/gitpod/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
